# Site
name: "Gallantries: Galaxy meets Carpentries"
description: Bridging Galaxy with the Carpentries for Genomics Training
meta_description: "Galaxy and Carpentries deliver Genomics Training"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl:
email: 'shiltemann@gmail.com'
#google_analytics: 'UA-134263619-1'
#disqus: 'demowebsite'

# Authors
authors:
  saskia:
    name: Saskia Hiltemann
    display_name: Saskia Hiltemann
    github: shiltemann
    email: shiltemann@gmail.com
    web: https://shiltemann.github.io
    twitter: https://twitter.com/shiltemann
    description: "Bioinformatician, Galaxy trainer, Galaxy tool developer."
  berenice:
    name: Bérénice Batut
    display_name: Bérénice Batut
    github: bebatut
    email:
    web: http://bebatur.fr
    twitter: https://twitter.com/bebatut
    description: ""
  helena:
    name: Helena Rasche
    display_name: Helena Rasche
    github: erasche
    email: hxr@informatik.uni-freiburg.de
    description: UseGalaxy.eu Administrator, Bioinformatician, Galaxy Trainer, Galaxy Tool Developer

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Other
markdown: kramdown
highlighter: rouge
