# Site
title: "Gallantries"
description: >
  When Galaxy meets Carpentries to develop Scalable, Modular, Eco-friendly, COVID-ready Bioinformatics Curricula
logo: 'assets/images/gallantries-logo-with-word-large.svg'
repository: galaxy-carpentries/gallantries
gitter: galaxy-carpentries/community

# Plugins
plugins: []

collections:
  posts:
    permalink: /posts/:year/:month/:day/:title/
  events:
    permalink: /event/:path/
    output: true

includes_dir: .